services:
  api:
    container_name: EventPilotContainer
    build:
      context: .
      dockerfile: src/EventPilot.API/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
#    volumes:
#      - ./src/EventPilot.Infrastructure/Data:/app/Data/
#      - ./src/EventPilot.Infrastructure/Data:/app

