services:
  api:
    container_name: EventPilotContainer
    build:
      context: .
      dockerfile: src/EventPilot.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__Default: Data Source=/app/Data/prod.db
    env_file:
      - .env
    volumes:
      - ./src/EventPilot.Infrastructure/Data:/app/Data
